#
#Please install following utilities
#selenium module for python
#webdriver for chrome browser
#
#Visit below links for more help
#http://selenium-python.readthedocs.io/
#https://sites.google.com/a/chromium.org/chromedriver/getting-started
#https://medium.com/@dawran6/twitter-scraper-tutorial-with-python-requests-beautifulsoup-and-selenium-part-2-b38d849b07fe#.vsvj5uizr

import csv
import time
import string
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

try:
    browser = webdriver.Chrome()
except:
    print("Exception in loading chrome driver")
    
with open('twitter-advanced-search-url.txt') as f:
    content = f.readline()
# you may also want to remove whitespace characters like `\n` at the end of each line
content = content.strip()

base_url = u'https://twitter.com/search?q='
#
#Search Query Generated by Twitter Advanced Search should be mentioned here
#To generate query go to https://twitter.com/search-advanced?lang=en
#
query = u'%23jallikattu%20to%3Apmoindia%20%40pmoindia%20since%3A2017-01-20%20until%3A2017-01-21'

#url = base_url + query

url = content
try:
    browser.get(url)
    time.sleep(1)
except:
    print("Exception in loading browser")

try:
    body = browser.find_element_by_tag_name('body')
except:
    print("Exception in loading twitter")

#Number of times pages needs to scroll for more tweets
for _ in range(50):
    body.send_keys(Keys.PAGE_DOWN)
    time.sleep(2)
    
tweets = browser.find_elements_by_class_name('tweet')

csv_file_name =  time.strftime("%Y-%m-%d-%H-%M") + '-tweets.csv'

f = open(csv_file_name, 'wt', encoding='utf-8')
try:
    writer = csv.writer(f)
    #print message on console
    print("tweet_id,username,text,time")
    #write to csv file
    writer.writerow( ('tweet_id', 'username', 'text', 'time') )
    
    for tweet in tweets:
        tweet_id = tweet.get_attribute('data-tweet-id')
        username = tweet.find_element_by_class_name('username').text
        #encode string to write in csv file
        #tweet_text = tweet.find_element_by_class_name('tweet-text').text.encode('utf-8')
        #tweet_text = tweet.find_element_by_class_name('tweet-text').text.decode('unicode-escape')
        tweet_text = tweet.find_element_by_class_name('tweet-text').text
        time = tweet.find_element_by_class_name('tweet-timestamp').get_attribute('title')
        print("%s,%s,%s,%s" % (tweet_id,username,tweet_text,time))
        writer.writerow( (tweet_id, username, tweet_text, time) )
finally:
    f.close()